apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fwgn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0040-tenant/tkrw-pr712-0075-0040-app/devfile-sample-fwgn@sha256:e8289f330971f9be8f01c4eb1d2d1e2dddd1ccc06005517c3a1a62785d3515ed
        name: my-nodejs
        resources: {}
status: {}
